# Generated by Django 4.1.5 on 2023-03-09 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasmi')),
                ('content', models.TextField(verbose_name="to'garak haqida")),
                ('phone', models.IntegerField(default='+998 (99) 999-99-99', max_length=12, verbose_name='Tel raqami')),
                ('price', models.IntegerField(null=True, verbose_name='Narxi')),
            ],
            options={
                'verbose_name': 'circle',
                'verbose_name_plural': 'circles',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasmi')),
                ('content', models.TextField(verbose_name='Yangilik haqida')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana')),
            ],
            options={
                'verbose_name': 'new',
                'verbose_name_plural': 'news',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Ismi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasmi')),
                ('content', models.TextField(verbose_name="O'qituvchi haqida")),
                ('position', models.CharField(max_length=100, verbose_name='Lavozimi')),
                ('phone', models.IntegerField(max_length=12, verbose_name='Tel raqami')),
                ('director', models.BooleanField(default=False, verbose_name='Direktor')),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
            },
        ),
    ]
