# Generated by Django 4.1.5 on 2023-03-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.IntegerField(default=0, verbose_name="O'quvchilar soni")),
                ('certif', models.IntegerField(default=0, verbose_name="Sertifikatli o'qituvchilar soni")),
                ('teacher', models.IntegerField(default=0, verbose_name="O'qituvchilar soni")),
                ('klas', models.IntegerField(default=0, verbose_name='Sinflar soni')),
            ],
        ),
    ]
