# Generated by Django 4.1.5 on 2023-03-10 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_circle_phone_alter_teacher_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana'),
        ),
    ]
