# Generated by Django 4.1.5 on 2023-03-10 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_circle_date_teacher_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Rasm')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana')),
            ],
            options={
                'verbose_name': 'Instagram',
                'verbose_name_plural': 'Instagrams',
            },
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'info', 'verbose_name_plural': 'infos'},
        ),
    ]
