# Generated by Django 4.1.5 on 2023-03-14 04:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_instagram_alter_info_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Rasm')),
                ('birthday', models.DateTimeField(null=True, verbose_name="tug'ilgan sanasi")),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Telefoni')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresi')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana')),
            ],
            options={
                'verbose_name': 'director',
                'verbose_name_plural': 'directors',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Rasm')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Rasm')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana')),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
            },
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='director',
        ),
        migrations.AddField(
            model_name='info',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name="Maktab yo'nalishi haqida qisqacha"),
        ),
        migrations.AddField(
            model_name='new',
            name='country',
            field=models.BooleanField(default=False, verbose_name='Chet el bilan shartnoma'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='sertificat',
            field=models.BooleanField(default=False, verbose_name='Sertifikat'),
        ),
    ]
