# Generated by Django 4.1.7 on 2023-03-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_director_event_meeting_remove_teacher_director_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='name',
            new_name='title',
        ),
    ]
